# The size of the field of the game, in pixels.
SCREEN_WIDTH = 1500
SCREEN_HEIGHT = 700

#SETTINS
FPS=1/60
FPS_SET_VELOCITY=1/15

#PATH ICONE
ROOT_FOLDER_IMAGE="assets/images/"
PATH_CANNON=ROOT_FOLDER_IMAGE+"cannon.png"
PATH_TARGET=ROOT_FOLDER_IMAGE+"target.png"
PATH_BULLET=ROOT_FOLDER_IMAGE+"bullet.png"
PATH_BOMB=ROOT_FOLDER_IMAGE+"bomb.png"
PATH_LASER=ROOT_FOLDER_IMAGE+"laser.png"
PATH_ROCK=ROOT_FOLDER_IMAGE+"rock.png"
PATH_UNIPV=ROOT_FOLDER_IMAGE+"logo unipv.png"
PATH_TITLE=ROOT_FOLDER_IMAGE+"Vector.png"
PATH_BACK=ROOT_FOLDER_IMAGE+"background.png"
PATH_PLAY=ROOT_FOLDER_IMAGE+"play.png"
PATH_RECORD=ROOT_FOLDER_IMAGE+"record.png"
PATH_HELP=ROOT_FOLDER_IMAGE+"help.png"
PATH_STAR_GOLD=ROOT_FOLDER_IMAGE+"starGold.png"
PATH_STAR_SILVER=ROOT_FOLDER_IMAGE+"starSilver.png"
PATH_STAR_BRONZE=ROOT_FOLDER_IMAGE+"starBronze.png"
PATH_POWER=ROOT_FOLDER_IMAGE+"power.png"
PATH_MIRROR=ROOT_FOLDER_IMAGE+"mirror.png"
PATH_PERPETIO=ROOT_FOLDER_IMAGE+"perpetio.png"
PATH_WARMHOLE_IN=ROOT_FOLDER_IMAGE+"warmHoleIN.png"
PATH_WARMHOLE_OUT=ROOT_FOLDER_IMAGE+"warmHoleOUT.png"
PATH_EXPLOSION=ROOT_FOLDER_IMAGE+"explosion.gif"
PATH_HOME=ROOT_FOLDER_IMAGE+"home.png"
PATH_SAVE=ROOT_FOLDER_IMAGE+"save.png"
PATH_FILE_RECORDS="assets/records.json"

#CANNON
CANNON_POS={'center_x': 0.1, 'y': 0.07}
CANNON_SIZE=(0.15, 0.15)
CANNON_POWER_POS={'center_x': 0.1, 'y': 0.35}
CANNON_POWER_SIZE=(0.12, 0.07)

#TARGET
TARGET_POS={'center_x': 0.88, 'y': 0.05}
TARGET_SIZE=(0.09, 0.19)

#BULLET
BULLET_MASS=3
BULLET_RADIUS=50
BULLET_DRILL=0
BULLET_SIZE=(0.015, 0.07)
BULLET_INITIAL_SHOT=10
BULLET_POINTS=100
#BOMB
BOMB_MASS=5
BOMB_RADIUS=70
BOMB_DRILL=0
BOMB_INITIAL_SHOT=5
BOMB_SIZE=(0.03, 0.07)
BOMB_POINTS=400
#LASER
LASER_MASS=0
LASER_VEL=LASER_RADIUS=3
LASER_LENGTH=20
LASER_SIZE=10
LASER_INITIAL_SHOT=3
LASER_POINTS=800

#OBSTACLES ROCK
ROCK_SIZE=(0.1, 0.1)

#MIRRON SIZE
MIRROR_SIZE=(0.03, 0.1)

#AMMUNITION
INITAL_COUNTER=[BULLET_INITIAL_SHOT,BOMB_INITIAL_SHOT,LASER_INITIAL_SHOT]
AMMU_POINTS=(BULLET_POINTS,BOMB_POINTS,LASER_POINTS)

#INITIAL PAGE
ALUMN='Andrea Bolis'
MAT='535315'
PROF_NAME='Stefano Ferrari'
COUSRE_NAME='Computer Programming'

#GAME
INITIAL_POINT=10000
LEVEL_POINT=2000
MAX_LEVEL=5

#FONTS
PIXEL_REGULAR='assets/fonts/Pixellari.ttf'

#GIF 
EXPLOSION_SIZE=(0.03, 0.1)